### ISSUE TITLE
Not an issue just a big thanks

### ISSUE THREAD

**Issue by ghazal** [kevinsguides/joomla_examples#1]
Great article, well detailed and well explained and thorough.
Big tks.
NB: As I didn't find a readme.md file, I take the liberty to show the URL of the said article:
Creating Joomla Content Plugins (With Examples)
https://kevinsguides.com/guides/webdev/joomla4/ref/content-plugins-with-exs

**Comment by kevinsguides** [comment]
Thanks for the feedback, glad you found it useful. I added a readme.

Best
Kevin
